# Generated by Django 5.2 on 2025-05-10 06:36

import uyde_core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uyde_core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=uyde_core.storage.S3MediaStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]