# Generated by Django 5.2 on 2025-05-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uyde_core', '0003_remove_photo_url_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
    ]
