# Generated by Django 5.2 on 2025-05-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uyde_core', '0003_remove_photo_url_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('rent_out', 'Сдам'), ('sell', 'Продам'), ('rent_in', 'Сниму'), ('buy', 'Куплю')], default='rent_out', max_length=20),
        ),
    ]
