# Generated by Django 5.2 on 2025-05-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uyde_core', '0004_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('rent_out', 'Сдам'), ('sell', 'Продам')], default='rent_out', max_length=20),
        ),
    ]
