# Generated by Django 5.2 on 2025-05-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uyde_core', '0004_remove_photo_url'),
        ('uyde_core', '0006_review'),
    ]

    operations = [
    ]
